<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DoctorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $doctors = array(
            array(
                'id' => 1,
                'name' => 'RAMADAS MURMU',
                'email' => 'LFCD0001@lifefertilitycentre.com',
                'code' => 'LFCD0001',
                'password' => '$2y$10$x34m1WypERvLoN3IyB2yeOElsQWElEwrA99KgO4C5Uw/AtJaLs38i',
                'designation_id' => NULL,
                'department_id' => 2,
                'company_id' => 1,
                'address' => NULL,
                'contact_no' => NULL,
                'dob' => '2002-07-22',
                'doj' => '2002-07-22',
                'qualification' => 'DMRD',
                'visiting_charge' => '500',
                'availablility' => 'FRIDAY',
                'email_verified_at' => '2022-07-22 05:29:34',
                'contract_type_id' => 0,
                'salary' => NULL,
                'slug' => NULL,
                'image' => '202207222208consultant.png',
                'remember_token' => NULL,
                'created_at' => '2022-07-22 05:29:37',
                'updated_at' => '2022-08-17 15:26:36',
            ),
            array(
                'id' => 2,
                'name' => 'ARIJIT BISWAS',
                'email' => 'LFCD0002@lifefertilitycentre.com',
                'code' => 'LFCD0002',
                'password' => '$2y$10$ElqVuNjXZx2gmgtel.jYyeOBwP3IRKECUruPAt5EpqdjUnngWadO2',
                'designation_id' => NULL,
                'department_id' => 1,
                'company_id' => 1,

                'address' => NULL,
                'contact_no' => NULL,
                'dob' => '2002-08-17',
                'doj' => '2022-08-01',
                'qualification' => 'CBAT',
                'visiting_charge' => NULL,
                'availablility' => NULL,
                'email_verified_at' => NULL,
                'contract_type_id' => 0,
                'salary' => NULL,
                'slug' => NULL,
                'image' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-08-17 15:27:37',
                'updated_at' => '2022-08-17 15:27:37',
            ),
            array(
                'id' => 3,
                'name' => 'ANUSHREE KARMAKAR',
                'email' => 'LFCD0003@lifefertilitycentre.com',
                'code' => 'LFCD0003',
                'password' => '$2y$10$NeiCjXbSrbZg5leflvWY5uvyqb9UAKW8MgCay20IKCMH19eq1OP2O',
                'designation_id' => NULL,
                'department_id' => 1,
                'company_id' => 1,

                'address' => NULL,
                'contact_no' => NULL,
                'dob' => '2002-08-17',
                'doj' => '2022-08-17',
                'qualification' => 'CBAT',
                'visiting_charge' => NULL,
                'availablility' => NULL,
                'email_verified_at' => NULL,
                'contract_type_id' => 0,
                'salary' => NULL,
                'slug' => NULL,
                'image' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-08-17 15:28:21',
                'updated_at' => '2022-08-17 15:28:21',
            ),
            array(
                'id' => 4,
                'name' => 'PRIYANKA KARMAKAR',
                'email' => 'LFCD0004@lifefertilitycentre.com',
                'code' => 'LFCD0004',
                'password' => '$2y$10$JLlPJRCn7Y84QJN6gpSIb.LBvniUpEyV1OsdRczGwiLcWTBabYveq',
                'designation_id' => NULL,
                'department_id' => 1,
                'company_id' => 1,

                'address' => NULL,
                'contact_no' => NULL,
                'dob' => '2002-08-17',
                'doj' => '2022-08-01',
                'qualification' => 'CBAT',
                'visiting_charge' => NULL,
                'availablility' => NULL,
                'email_verified_at' => NULL,
                'contract_type_id' => 0,
                'salary' => NULL,
                'slug' => NULL,
                'image' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-08-17 15:29:19',
                'updated_at' => '2022-08-17 15:29:19',
            ),
            array(
                'id' => 5,
                'name' => 'ABHINAV SAKET',
                'email' => 'LFCD0005@lifefertilitycentre.com',
                'code' => 'LFCD0005',
                'password' => '$2y$10$/uF3j/zVRifklv.xib//0u.JpUtGaVc.pTgcivzkAFS/Del2NEY.2',
                'designation_id' => NULL,
                'department_id' => 2,
                'company_id' => 1,

                'address' => NULL,
                'contact_no' => NULL,
                'dob' => '2002-08-17',
                'doj' => '2022-08-17',
                'qualification' => 'MD',
                'visiting_charge' => NULL,
                'availablility' => NULL,
                'email_verified_at' => NULL,
                'contract_type_id' => 0,
                'salary' => NULL,
                'slug' => NULL,
                'image' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-08-17 15:30:00',
                'updated_at' => '2022-08-17 15:30:18',
            ),
            array(
                'id' => 6,
                'name' => 'C JAIN',
                'email' => 'LFCD0006@lifefertilitycentre.com',
                'code' => 'LFCD0006',
                'password' => '$2y$10$0irvbmoEqQo2i1X0kbfqY.W7LHwLeWU22Zjjsje.JdyldkucwaaA6',
                'designation_id' => NULL,
                'department_id' => 2,
                'company_id' => 1,

                'address' => NULL,
                'contact_no' => NULL,
                'dob' => '2002-08-17',
                'doj' => '2022-08-01',
                'qualification' => 'DNB',
                'visiting_charge' => NULL,
                'availablility' => NULL,
                'email_verified_at' => NULL,
                'contract_type_id' => 0,
                'salary' => NULL,
                'slug' => NULL,
                'image' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-08-17 15:31:26',
                'updated_at' => '2022-08-17 15:31:39',
            ),
            array(
                'id' => 7,
                'name' => 'DEBCHANDAN ROY',
                'email' => 'LFCD0007@lifefertilitycentre.com',
                'code' => 'LFCD0007',
                'password' => '$2y$10$y5o5dwNOvNO1ojZwVsC6XOgSc8s28nUhJ.01VhvNviayO9L6DaPjS',
                'designation_id' => NULL,
                'department_id' => 1,
                'company_id' => 1,

                'address' => NULL,
                'contact_no' => NULL,
                'dob' => '2002-08-17',
                'doj' => '2022-08-01',
                'qualification' => NULL,
                'visiting_charge' => NULL,
                'availablility' => NULL,
                'email_verified_at' => NULL,
                'contract_type_id' => 0,
                'salary' => NULL,
                'slug' => NULL,
                'image' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-08-17 15:32:23',
                'updated_at' => '2022-08-17 15:32:23',
            ),
        );
        foreach($doctors as $doctor){
            \App\Models\Doctor::create($doctor);
        }

    }
}
